Support Distinct function in query
prest/adapters pull request #20
Opened 2017-10-03 15:56 UTC by bege13mot

This PR introduces support for the Distinct function in the query string. This hopefully solves prest/prest#221.

2017-10-03 16:04 UTC, felipeweb requested changes
i think the better way to implement this is create `?_distinct=true`

2017-10-03 16:11 UTC, bege13mot commented
Sorry, @felipeweb I'm new in golang and in this project. Could you please provide me an example? It isn't clear for me now.

2017-10-03 16:52 UTC, felipeweb commented
@bege13mot  a new param in query string called distinct

2017-10-03 17:37 UTC, lerrua commented
@bege13mot great PR, but as @felipeweb wrote above it's better change distinct to `_distinct` to follow others query params. You can see our examples here: https://postgres.rest/query-statements/

2017-10-04 04:03 UTC, avelino requested changes

2017-10-04 04:03 UTC, avelino commented on postgres/postgres.go
> +		}
run gofmt pls

2017-10-04 09:32 UTC, bege13mot commented
Thank you @felipeweb and @lerrua for the explanations. Hope my new pull request will be better.

2017-10-04 09:34 UTC, closed without merging