Modifications to make the pREST compatible with other adapters
prest/adapters pull request #32
Opened 2018-01-18 12:48 UTC by joelmdesouza

prest/prest#269

2018-01-18 23:22 UTC, felipeweb requested changes
need to add functions for the database and schema endpoint

2018-01-26 16:20 UTC, joelmdesouza commented
So @felipeweb , statements.DatabasesSelect is already encapsulated within Adapter.DatabaseClause and statements.SchemasSelect encapsulated in Adapter.SchemaClause.
I believe these are the comparable functions I've created.

2018-02-02 19:45 UTC, felipeweb approved these changes

2018-02-02 19:47 UTC, merged

2018-02-02 20:01 UTC, felipeweb commented
yes @joelmdesouza  you are right