Fix problem with fields permissions
prest/adapters pull request #4
Opened 2017-07-27 14:10 UTC by marioidival

retalted #2

2017-07-27 14:31 UTC, felipeweb requested changes

2017-07-27 14:31 UTC, felipeweb commented on postgres/postgres.go
> +			gf, err := normalizeColumn(col)
it  can be refactored we will do it together

2017-07-28 04:55 UTC, felipeweb approved these changes

2017-07-28 09:42 UTC, marioidival commented
LGTM

2017-07-28 11:09 UTC, avelino approved these changes
LGTM

2017-07-28 13:01 UTC, merged