TablePermissions respect prest conf
prest/adapters pull request #46
Opened 2018-06-26 18:54 UTC by cassiobotaro

* rewrite TablePermissions method to respect prest config
* remove hasPermission from Item struct
* change addItem signature without table permission

Related to https://github.com/prest/prest/issues/309

2018-06-26 18:55 UTC, golangci commented on mock/mock_test.go
> +		{"add item", args{[]byte(`[]`), nil, false}, 1},
github.com/prest/adapters/mock.args composite literal uses unkeyed fields

2018-06-26 18:56 UTC, felipeweb requested changes
Travis is broken

2018-06-26 19:35 UTC, felipeweb approved these changes

2018-06-27 14:14 UTC, crgimenes approved these changes
LGTM

2018-06-27 14:14 UTC, merged